# Generated by Django 5.2.17 on 2026-08-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('slug', models.SlugField(help_text="Identifiant court utilisé dans les URLs : 'github', 'gitlab'…", max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('authorization_url', models.URLField(help_text='Ex. https://github.com/login/oauth/authorize', max_length=500)),
                ('token_url', models.URLField(help_text='Ex. https://github.com/login/oauth/access_token', max_length=500)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True, default='')),
                ('default_scopes', models.CharField(blank=True, help_text='Portées demandées par défaut, séparées par des espaces.', max_length=500)),
                ('scope_separator', models.CharField(default=' ', help_text='Séparateur attendu par le site dans le paramètre `scope`.', max_length=4)),
                ('use_pkce', models.BooleanField(default=False, help_text="Ajoute PKCE S256 à l'aller-retour avec le site. GitHub ne le supporte pas pour les OAuth Apps ; GitLab et Google, oui.")),
                ('account_url', models.URLField(blank=True, help_text="Optionnel — endpoint renvoyant le profil du compte connecté (ex. https://api.github.com/user). Sert uniquement à afficher à l'utilisateur QUEL compte il a relié.", max_length=500)),
                ('account_label_field', models.CharField(blank=True, default='login', help_text="Champ JSON de la réponse `account_url` à afficher ('login', 'email'…).", max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="Aide-mémoire pour les devs : où l'app est enregistrée, par qui…")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.EmailField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'providers',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PendingAuthorization',
            fields=[
                ('state', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('code_verifier', models.CharField(blank=True, max_length=128)),
                ('return_url', models.URLField(blank=True, help_text='Où renvoyer le navigateur une fois la connexion établie.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
            options={
                'db_table': 'pending_authorizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_type', models.CharField(default='bearer', max_length=40)),
                ('scope', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_label', models.CharField(blank=True, help_text='Identité côté site (login GitHub…), pour affichage seulement.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.provider')),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['provider_id', 'user_email'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'user_email'), name='uniq_connection_per_user_provider')],
            },
        ),
    ]
